# Generated by Django 4.0.1 on 2022-02-06 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_clientmessage_appearance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmessage',
            name='appearance_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='appearance_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата появления'),
        ),
    ]
