# Generated by Django 4.0.1 on 2022-02-06 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_clientmessage_appearance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, verbose_name='Опубликовать'),
        ),
    ]
