version: '3.8.3'
services:
  web:
#    container_name: web
#    hostname: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
#      - ./server/:/usr/src/server/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
#      - es
  db:
#    container_name: db
#    hostname: db
    image: postgres:12.0-alpine # позже заменить на 14-ую версию
    env_file:
      - ./.env.dev
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#      - ./data/db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=322322
#      - POSTGRES_DB=insure_brother

#  es:
#    image: elasticsearch:7.8.1
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"

#volumes:
#  postgres_data:
