version: '3.8.3'
services:
  web:
    container_name: web
    hostname: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - rabbit
      - es
  db: # Не получилось подлючить volumes к postgres
    container_name: db
    hostname: db
    image: postgres:12.0-alpine
    env_file:
      - ./.env.dev
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#      - ./data/db:/var/lib/postgresql/data
  rabbit:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:3.8.19-management
    env_file:
      - ./.env.dev
    ports:
      - "5672:5672"
      - "15672:15672"
  celery:
    container_name: celery
    hostname: celery
    build: .
    command: celery -A server worker -l INFO
    volumes:
      - .:/code
    env_file:
      - ./.env.dev
    depends_on:
      - rabbit
  celery-beat:
    container_name: celery-beat
    hostname: celery-beat
    build: .
    command: celery -A server beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    env_file:
      - ./.env.dev
    depends_on:
      - rabbit
  es:
    container_name: es
    hostname: es
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

#volumes:
#  postgres_data:
